// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVdipOzB3qgUPcXpo4IAM1jhCRmjLSbAY',
    appId: '1:129080420760:web:d49f5f20834309008c23ed',
    messagingSenderId: '129080420760',
    projectId: 'habit-dashboard-df646',
    authDomain: 'habit-dashboard-df646.firebaseapp.com',
    storageBucket: 'habit-dashboard-df646.firebasestorage.app',
    measurementId: 'G-2X2SFDKDBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYwQk0LnGA4CT1unx5Eap4RQyhulWZXA',
    appId: '1:129080420760:android:eb4f3c13da6171f48c23ed',
    messagingSenderId: '129080420760',
    projectId: 'habit-dashboard-df646',
    storageBucket: 'habit-dashboard-df646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhB4Ce5T8I-p_dQgFwRe6vJoxJQyRLHM',
    appId: '1:129080420760:ios:1bf72b1123d1a7a48c23ed',
    messagingSenderId: '129080420760',
    projectId: 'habit-dashboard-df646',
    storageBucket: 'habit-dashboard-df646.firebasestorage.app',
    iosBundleId: 'com.example.habitDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhB4Ce5T8I-p_dQgFwRe6vJoxJQyRLHM',
    appId: '1:129080420760:ios:1bf72b1123d1a7a48c23ed',
    messagingSenderId: '129080420760',
    projectId: 'habit-dashboard-df646',
    storageBucket: 'habit-dashboard-df646.firebasestorage.app',
    iosBundleId: 'com.example.habitDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVdipOzB3qgUPcXpo4IAM1jhCRmjLSbAY',
    appId: '1:129080420760:web:c2861865d49289078c23ed',
    messagingSenderId: '129080420760',
    projectId: 'habit-dashboard-df646',
    authDomain: 'habit-dashboard-df646.firebaseapp.com',
    storageBucket: 'habit-dashboard-df646.firebasestorage.app',
    measurementId: 'G-TB1R2SPT6Z',
  );
}